spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    gcp:
      storage:
        url: https://storage.googleapis.com/${BUCKET_NAME}/
        credentials:
          location: ${GCP_KEY_PATH}
        project-id: ${GCP_PROJECT_ID}
        bucket: ${BUCKET_NAME}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

admin:
  password: ${ADMIN_PASSWORD}